"""
Django settings for audition_backend project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$n*$aa3@%9o!df!w#r44y$r+@me+8*)+$ylh9s2yfxb4#klu=p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

#ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = ['.ccanitd.in','3.110.184.223','valorant-gaming.vercel.app',...,'localhost',]
GOOGLE_RECAPTCHA_SITE_KEY = '6LeK3F0cAAAAAELH7R-yCDyDuKuK57DnNRqUmh6C'
GOOGLE_RECAPTCHA_SITE_KEY2 = '6LfDoLEpAAAAAI3LGKc65_BVrEF6FnLgby2uNFv-'

GOOGLE_RECAPTCHA_SECRET_KEY = '6LeK3F0cAAAAAFWFQOjiu04zshBydjnNuf-lB893'
GOOGLE_RECAPTCHA_SECRET_KEY2 = '6LfDoLEpAAAAABwOHtKtNR-_s9FVKDLIJyyKuWp0'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'auditionApp',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'import_export',
    'axes',
]

AUTHENTICATION_BACKENDS = [
    # AxesBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
    'axes.backends.AxesBackend',

    # Django ModelBackend is the default authentication backend.
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware', #this should be at the last position
]

ROOT_URLCONF = 'audition_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'audition_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

#DATABASES = {
# 'default': {
#     'ENGINE': 'django.db.backends.postgresql_psycopg2',
#     'NAME': 'audition',
#     'USER': 'ubuntu',
#     'PASSWORD': 'glugKeBaapHamHain',
#     'HOST': 'localhost',
#     'PORT': '',
#  }

#}

# DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'NAME': 'ccaaudition2024',
    #     'USER': 'gayatriaudition',
    #     'PASSWORD': 'ccaAuditionGAYATRI2024',
    #     'HOST': 'localhost',
    #     'PORT': '',
    # }
    
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'ccaaudition2024',
        'USER': 'gayatriaudition',
        'PASSWORD': 'ccaAuditionGAYATRI2024',
        'HOST': 'localhost',
        'PORT': '',
    }
}

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS':
    ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAdminUser',
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
    ],
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = 'wdct@ccanitd.in'
# W'  # write ur email id between ' '
EMAIL_HOST_PASSWORD = 'igicepeavscxpsha'  # write ur password here between ' '
EMAIL_USE_TLS = True

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True
USE_L10N = True
USE_TZ = True

CORS_ALLOWED_ORIGINS = [
    "https://www.ccanitd.in","http://localhost:3000","https://workshop.ccanitd.in","https://ccanitd.in","https://valorant-gaming.vercel.app"
]

AXES_ENABLED = True
AXES_IP_BLACKLIST = None # ['0.0.0.0']
AXES_NEVER_LOCKOUT_GET = True
AXES_FAILURE_LIMIT = 5

AXES_BEHIND_REVERSE_PROXY = True
AXES_COOLOFF_TIME = 168 # hours - after this time the old failed login attempts will be deleted
AXES_PROXY_COUNT = 1
AXES_META_PRECEDENCE_ORDER = [
   'HTTP_X_FORWARDED_FOR',
   'REMOTE_ADDR',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'