# Generated by Django 4.0.1 on 2022-01-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditionPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('roll_no', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=10, unique=True)),
                ('year', models.CharField(max_length=50, null=True)),
                ('branch', models.CharField(max_length=200, null=True)),
                ('cca_ques1', models.TextField(null=True)),
                ('cca_ques2', models.TextField(null=True)),
                ('ecell_ques1', models.TextField(null=True)),
                ('rnd_ques', models.TextField(null=True)),
                ('f_of_interest_ques', models.TextField(null=True)),
                ('prj_ques', models.TextField(null=True)),
                ('robo_ques1', models.TextField(null=True)),
                ('robo_ques2', models.TextField(null=True)),
                ('schl_prj', models.TextField(null=True)),
                ('daily_prbs', models.TextField(null=True)),
                ('ecell_ques2', models.TextField(null=True)),
                ('wdct_ques1', models.TextField(null=True)),
                ('wdct_ques2', models.TextField(null=True)),
                ('wdct_ques3', models.TextField(null=True)),
                ('arhn_logo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('logo_expln', models.TextField(null=True)),
                ('choice1', models.CharField(max_length=50, null=True)),
                ('choice2', models.CharField(max_length=50, null=True)),
                ('choice3', models.CharField(max_length=50, null=True)),
                ('choice4', models.CharField(max_length=50, null=True)),
                ('choice5', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
