# Generated by Django 4.0.1 on 2022-01-31 13:57

import auditionApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditionApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditionportal',
            old_name='cca_ques1',
            new_name='cca1',
        ),
        migrations.RenameField(
            model_name='auditionportal',
            old_name='cca_ques2',
            new_name='cca2',
        ),
        migrations.RenameField(
            model_name='auditionportal',
            old_name='daily_prbs',
            new_name='common',
        ),
        migrations.RenameField(
            model_name='auditionportal',
            old_name='ecell_ques1',
            new_name='core1',
        ),
        migrations.RenameField(
            model_name='auditionportal',
            old_name='branch',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='auditionportal',
            old_name='ecell_ques2',
            new_name='ecell1',
        ),
        migrations.RenameField(
            model_name='auditionportal',
            old_name='f_of_interest_ques',
            new_name='ecell2',
        ),
        migrations.RenameField(
            model_name='auditionportal',
            old_name='logo_expln',
            new_name='rnd1',
        ),
        migrations.RenameField(
            model_name='auditionportal',
            old_name='prj_ques',
            new_name='rnd2',
        ),
        migrations.RenameField(
            model_name='auditionportal',
            old_name='rnd_ques',
            new_name='rnd3',
        ),
        migrations.RenameField(
            model_name='auditionportal',
            old_name='robo_ques1',
            new_name='robo1',
        ),
        migrations.RenameField(
            model_name='auditionportal',
            old_name='robo_ques2',
            new_name='robo2',
        ),
        migrations.RenameField(
            model_name='auditionportal',
            old_name='schl_prj',
            new_name='wdct1',
        ),
        migrations.RenameField(
            model_name='auditionportal',
            old_name='wdct_ques1',
            new_name='wdct2',
        ),
        migrations.RenameField(
            model_name='auditionportal',
            old_name='wdct_ques2',
            new_name='wdct3',
        ),
        migrations.RenameField(
            model_name='auditionportal',
            old_name='wdct_ques3',
            new_name='wdct4_logo_explain',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='arhn_logo',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='year',
        ),
        migrations.AddField(
            model_name='auditionportal',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='auditionportal',
            name='wdct4_logo',
            field=models.ImageField(blank=True, null=True, upload_to=auditionApp.models.audition_image_path),
        ),
    ]
