# Generated by Django 4.0.1 on 2022-01-31 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditionApp', '0002_rename_cca_ques1_auditionportal_cca1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditionportal',
            name='common',
        ),
    ]
