# Generated by Django 4.0.1 on 2022-01-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditionApp', '0003_remove_auditionportal_common'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditionportal',
            name='cca1',
            field=models.TextField(help_text='Why do you want to join Centre for Cognitive Activities (CCA)?', null=True),
        ),
        migrations.AlterField(
            model_name='auditionportal',
            name='cca2',
            field=models.TextField(help_text='According to you, what makes you suitable for being a member of CCA?', null=True),
        ),
        migrations.AlterField(
            model_name='auditionportal',
            name='core1',
            field=models.TextField(help_text='Do you happen to have any previous managerial experience? Have you ever been involved in conducting any event? If yes, write about your role briefly.', null=True),
        ),
        migrations.AlterField(
            model_name='auditionportal',
            name='ecell1',
            field=models.TextField(help_text='Write about any daily-life problems that you might have experienced yourself or seen others struggling with the same issues. Can you come up with any ideas to solve it?', null=True),
        ),
        migrations.AlterField(
            model_name='auditionportal',
            name='ecell2',
            field=models.TextField(help_text='What do you understand by a Start-up and entrepreneurship? Do you have any entrepreneurial qualities/skills? Briefly write about those skills.', null=True),
        ),
        migrations.AlterField(
            model_name='auditionportal',
            name='email2',
            field=models.EmailField(blank=True, help_text='Secondary Email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='auditionportal',
            name='rnd1',
            field=models.TextField(help_text='Are you interested in Research and Development (RnD) ? Explain', null=True),
        ),
        migrations.AlterField(
            model_name='auditionportal',
            name='rnd2',
            field=models.TextField(help_text='What is your field of interest? How you will rate the extent of your knowledge in the respective field (Scale: 0-10)?', null=True),
        ),
        migrations.AlterField(
            model_name='auditionportal',
            name='rnd3',
            field=models.TextField(help_text='Any project that you have worked on previously? (If yes, briefly describe the project)', null=True),
        ),
        migrations.AlterField(
            model_name='auditionportal',
            name='robo1',
            field=models.TextField(help_text='Are you interested in robotics? What do you know about robotics?', null=True),
        ),
        migrations.AlterField(
            model_name='auditionportal',
            name='robo2',
            field=models.TextField(help_text='Have you done any projects in school ? Explain in Brief.', null=True),
        ),
        migrations.AlterField(
            model_name='auditionportal',
            name='wdct1',
            field=models.TextField(help_text='What are the programming languages that you know? What are the web development and app development technologies you know and what are some of your favourite websites and apps?', null=True),
        ),
        migrations.AlterField(
            model_name='auditionportal',
            name='wdct2',
            field=models.TextField(help_text='Have you any experience with video editing softwares? If yes, what software do you prefer? Did you work in any such project recently? What are your experiences with other video editing software?', null=True),
        ),
        migrations.AlterField(
            model_name='auditionportal',
            name='wdct3',
            field=models.TextField(help_text='Do you like making posters, comic strips, etc? Does design projects like UI/UX, motion graphics, visual or graphic design interest you? Are you familiar with any graphic design software or would like to work with one? How do you incorporate feedback into your work?', null=True),
        ),
        migrations.AlterField(
            model_name='auditionportal',
            name='wdct4_logo_explain',
            field=models.TextField(help_text='Design the AAROHAN logo based on any theme of your choice and explain in brief your thought process behind it.', null=True),
        ),
    ]
