# Generated by Django 4.0.1 on 2023-01-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditionApp', '0004_alter_auditionportal_cca1_alter_auditionportal_cca2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditionportal',
            name='cca1',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='cca2',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='choice4',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='choice5',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='core1',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='ecell1',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='ecell2',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='rnd1',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='rnd2',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='rnd3',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='robo1',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='robo2',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='wdct1',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='wdct2',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='wdct3',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='wdct4_logo',
        ),
        migrations.RemoveField(
            model_name='auditionportal',
            name='wdct4_logo_explain',
        ),
        migrations.AddField(
            model_name='auditionportal',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
