# Generated by Django 4.0.1 on 2023-01-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditionApp', '0005_remove_auditionportal_cca1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditionportal',
            name='uid',
        ),
    ]
