# Generated by Django 4.0.1 on 2023-01-27 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditionApp', '0006_remove_auditionportal_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditionportal',
            old_name='gender',
            new_name='year',
        ),
    ]
