# Generated by Django 4.0.1 on 2024-02-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditionApp', '0007_rename_gender_auditionportal_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditionportal',
            name='year',
        ),
    ]
