# Generated by Django 4.0.1 on 2024-03-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditionApp', '0009_designworkshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='BgmiGaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='bgmi_payment_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ValorantGaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='valo_payment_images/')),
            ],
        ),
    ]
